[tool.poetry]
name = "tetris-engine"
version = "0.1.0"
description = "guideline-compliant tetris engine"
authors = ["Sofia \"dzshn\" N. L. <zshn@pm.me>"]
license = "MIT"
packages = [
    { include = "tetris" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.4"
typing-extensions = "^4.0.1"

[tool.poetry.dev-dependencies]
tox = "^3.24.4"

[tool.black]

[tool.mypy]
check_untyped_defs = true
files = [
    "tetris/*.py"
]
python_version = "3.9"
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true

[tool.isort]
profile = "google"
force_sort_within_sections = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
